# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86bcfefa95720b8d363f6ec7a0c587bb68d2f524e8056f7a199b42dc384e66a00d107e3ba50818829a87325a1ffee6305c4228573c52b82ce7064c92a4903311

test:
  secret_key_base: ac727e94b20d63000aa9f77e2c59df0f0a7793810c8b171bee06232d778662efd28b381d2fd81dd8f7a92c4ab99aee3dfa5c64333d18e2c5676b0d0d74b0dd7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
